from django.urls import path
from .views import (
    AssignedChefView,
    AssignChefView,
    ChefListView,
    ChefConsoleAvailabilityView,
    ChefConsoleChefsView,
    ChefConsoleDashboardView,
    ChefPartnerAvailabilityView,
    ChefPartnerHistoryView,
    ChefPartnerInstantRespondView,
    ChefPartnerServiceEndRequestView,
    ChefPartnerServiceEndVerifyView,
    ChefPartnerServiceJourneyStartView,
    ChefPartnerServiceStartRequestView,
    ChefPartnerServiceStartVerifyView,
    ChefPartnerLocationView,
    ChefPartnerMeView,
    ChefPartnerRegisterView,
    ChefPartnerSlotSettingsView,
    InstantChefLatestView,
    InstantChefRequestView,
    InstantChefRequestDetailView,
    InstantChefRespondView,
    UserInstantOrderFeedbackView,
    UserInstantOrderHistoryView,
    UserServiceOtpView,
)

urlpatterns = [
    path("", ChefListView.as_view()),
    path("assigned/", AssignedChefView.as_view()),
    path("assign/", AssignChefView.as_view()),
    path("instant/request/latest/", InstantChefLatestView.as_view()),
    path("instant/request/", InstantChefRequestView.as_view()),
    path("instant/request/<int:request_id>/", InstantChefRequestDetailView.as_view()),
    path("instant/request/<int:request_id>/respond/", InstantChefRespondView.as_view()),
    path("console/chefs/", ChefConsoleChefsView.as_view()),
    path("console/dashboard/", ChefConsoleDashboardView.as_view()),
    path("console/availability/", ChefConsoleAvailabilityView.as_view()),
    path("partner/register/", ChefPartnerRegisterView.as_view()),
    path("partner/me/", ChefPartnerMeView.as_view()),
    path("partner/availability/", ChefPartnerAvailabilityView.as_view()),
    path("partner/location/", ChefPartnerLocationView.as_view()),
    path("partner/slots/", ChefPartnerSlotSettingsView.as_view()),
    path("partner/history/", ChefPartnerHistoryView.as_view()),
    path("partner/instant/respond/", ChefPartnerInstantRespondView.as_view()),
    path("partner/service/start/request/", ChefPartnerServiceStartRequestView.as_view()),
    path("partner/service/start/verify/", ChefPartnerServiceStartVerifyView.as_view()),
    path("partner/service/journey/start/", ChefPartnerServiceJourneyStartView.as_view()),
    path("partner/service/end/request/", ChefPartnerServiceEndRequestView.as_view()),
    path("partner/service/end/verify/", ChefPartnerServiceEndVerifyView.as_view()),
    path("service/my/", UserServiceOtpView.as_view()),
    path("history/instant/", UserInstantOrderHistoryView.as_view()),
    path("history/instant/<int:history_id>/feedback/", UserInstantOrderFeedbackView.as_view()),
]
