# Generated by Django 6.0.1 on 2026-02-17 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0003_chef_latitude_chef_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantChefRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('searching', 'Searching'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('no_chef', 'No Chef Found')], default='searching', max_length=20)),
                ('meal', models.CharField(blank=True, default='', max_length=20)),
                ('wave', models.CharField(blank=True, default='', max_length=10)),
                ('request_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('request_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_km', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('current_offer_expires_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_instant_requests', to='chef.chef')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instant_chef_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstantChefOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('distance_km', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('skipped', 'Skipped')], default='queued', max_length=20)),
                ('offered_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instant_offers', to='chef.chef')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='chef.instantchefrequest')),
            ],
            options={
                'ordering': ['rank', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='instantchefrequest',
            index=models.Index(fields=['user', 'status', '-created_at'], name='chef_instan_user_id_9a2e3e_idx'),
        ),
        migrations.AddIndex(
            model_name='instantchefoffer',
            index=models.Index(fields=['request', 'status', 'rank'], name='chef_instan_request_8cd4d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='instantchefoffer',
            unique_together={('request', 'chef')},
        ),
    ]
