# Generated by Django 6.0.1 on 2026-02-25 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0005_chefpartnerprofile'),
        ('core', '0008_chefwavepolicy_custom_wave_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOtpSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('subscription', 'Subscription'), ('instant', 'Instant')], max_length=20)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('meal', models.CharField(blank=True, default='', max_length=20)),
                ('wave', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('start_otp_generated', 'Start OTP Generated'), ('in_progress', 'In Progress'), ('end_otp_generated', 'End OTP Generated'), ('completed', 'Completed')], default='assigned', max_length=30)),
                ('start_otp', models.CharField(blank=True, default='', max_length=6)),
                ('start_otp_generated_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('end_otp', models.CharField(blank=True, default='', max_length=6)),
                ('end_otp_generated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_otp_sessions', to='chef.chef')),
                ('instant_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_otp_session', to='chef.instantchefrequest')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_otp_sessions', to='core.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_otp_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['user', 'status', '-updated_at'], name='chef_servic_user_id_877e8a_idx'), models.Index(fields=['chef', 'status', '-updated_at'], name='chef_servic_chef_id_22bcc3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('subscription__isnull', False)), fields=('subscription', 'service_date', 'meal'), name='uniq_subscription_service_slot')],
            },
        ),
    ]
