# Generated by Django 6.0.1 on 2026-02-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0006_serviceotpsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceotpsession',
            name='journey_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
