# Generated by Django 6.0.1 on 2026-02-25 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0007_serviceotpsession_journey_started_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_started_at', models.DateTimeField(blank=True, null=True)),
                ('service_completed_at', models.DateTimeField(blank=True, null=True)),
                ('request_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('request_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instant_order_history', to='chef.chef')),
                ('instant_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history_entry', to='chef.instantchefrequest')),
                ('service_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instant_history_entry', to='chef.serviceotpsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instant_order_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='chef_instan_user_id_afbaac_idx'), models.Index(fields=['chef', '-created_at'], name='chef_instan_chef_id_c0067c_idx')],
            },
        ),
    ]
