# Generated by Django 6.0.1 on 2026-02-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_delete_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='activity_level',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='medical_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='target_weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
