# Generated by Django 6.0.1 on 2026-02-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_userpreference_activity_level_userpreference_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='cuisine_style',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
