# Generated by Django 6.0.1 on 2026-02-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_userpreference_cuisine_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='target_height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
