# Generated by Django 6.0.1 on 2026-02-17 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_userpreference_target_height_cm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='target_height_cm',
        ),
    ]
