# Generated by Django 6.0.1 on 2026-02-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_userpreference_target_height_cm'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='people_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
