# Generated by Django 6.0.1 on 2026-02-04 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0002_alter_chef_speciality_userchef'),
        ('core', '0003_subscription_chef_subscription_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='chef.chef'),
        ),
        migrations.AlterField(
            model_name='chefassignment',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef.chef'),
        ),
        migrations.DeleteModel(
            name='Chef',
        ),
    ]
