# Generated by Django 6.0.1 on 2026-02-17 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0003_chef_latitude_chef_longitude'),
        ('core', '0004_alter_subscription_chef_alter_chefassignment_chef_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='meal_wave',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ChefWavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_subscription_capacity', models.PositiveSmallIntegerField(default=3)),
                ('max_wave_capacity', models.PositiveSmallIntegerField(default=5)),
                ('allow_ondemand_extra', models.BooleanField(default=True)),
                ('chef', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wave_policy', to='chef.chef')),
            ],
        ),
    ]
