# Generated by Django 6.0.1 on 2026-02-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefwavepolicy',
            name='available_waves',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
