# Generated by Django 6.0.1 on 2026-02-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_chefwavepolicy_available_waves'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefwavepolicy',
            name='custom_wave_labels',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
